kenar = int(input("Enter one side of the square: "))
print("karenin alanı: " + (kenar * kenar))
kenarlar = int(input("Enter the long and short sides of the rectangle:\n"))  
liste = kenarlar.split(" ")          
print("Dikdörtgenin alanı: " + liste[0]*liste[1])
